tests/bug59378.phpt
Hi @mkoppanen,
Can you review and merge this test?
It says on https://bugs.php.net/bug.php?id=59378 that you were able to reproduce this issue....I am not able to, and the issue was reported on a no longer supported version of PHP.
If you can't repro the issue any longer, I think we can safely close the bug.
cheers
Dan
=> Added test for bug 59378, where writing to memory fails.

imagick.c, imagick_class.c, php_imagick_defs.h
These are required to set which directory ImageMagick uses as a temp directory.
I think it's much better to add these rather than trying to set the directory through an ini file setting as:
* ini settings generally suck in general, but particular as if something goes wrong there's no good way to debug it.
* It allows users of Imagick to set the temp directory programmatically rather than just being a single possible temp dir.
* It allows switching of temp dir at run time - e.g. if a single image process is running into problems, you could switch the temp dir for just that image manipulation.
=> Added access to the get/set registry functions.

imagick_class.c
The declarations of str_keys and arr_keys have to be before 'found = 0'.
=> Fix VC11 errors

imagemagick.m4
Debian 8 (Jessie) has this in its imagemagick changelog:
```
imagemagick (8:6.8.9.9-1) unstable; urgency=high
Obsolete config scripts (Magick-config, MagickCore-config,
MagickWand-config, Wand-config and Magick++-config) are
not multi-arch safe and thus have been removed from /usr/bin.
.
Moreover, these scripts are superseded by pkg-config
facilities.
.
However as a courtesy to our users, these scripts have
been moved to
/usr/lib/$DEB_HOST_MULTIARCH/ImageMagick-$VERSION/bin-$QUANTUMDEPTH/
where $DEB_HOST_MULTIARCH is the multi-arch triplet and
$QUANTUMDEPTH is the current quantum depth. $VERSION is the upstream
version without the revision number.
.
Please note that these scripts will be definitively removed after
jessie.
-- Bastien Roucariès <roucaries.bastien+debian@gmail.com>  Sun, 19 …
```
=> Support pkg-config

imagick.c
Sometime both version can differ (after an update of the library)
* headers version = buildtime
* library verison = runtime
ImageMagick headers version => ImageMagick 6.9.1-2 Q16 x86_64 2015-05-28 http://www.imagemagick.org
ImageMagick library version => ImageMagick 6.9.1-3 Q16 x86_64 2015-05-28 http://www.imagemagick.org
=> report headers and library version

imagick_class.c, tests/ceil.phpt
Hello,
we encountered an issue with the calculation of "cropThumbnailImage", we were expecting e.g. 250x250 images but sometimes we were getting 249x250. I found out that in some cases the rounding is not accurate. In our example it was "249,999768". For my understanding it is enough to add "ceil" to round the value to the next number. I did some tests with random values for width / height and it never failed with the fix.
I modified only "imagick_class.c"  and i have added one test file to confirm that it's working as expected. You can also run my test against the current version, it will fail with "width 249" instead of 250.
Please let me know if i missed something.
Michael
=> Rounding fix for cropThumbnailImage

imagick.c
zend_exception_get_default() has been deprecated (line 48 of zend-exceptions.h) in favor of using zend_ce_exception directly.
=> Change exception class entries for zend engine 3

config.m4, examples/polygon.php, imagemagick.m4, imagick.c, imagick_class.c, imagick_file.c, imagick_helpers.c, imagickdraw_class.c, imagickpixel_class.c, imagickpixeliterator_class.c, package.xml, php_imagick.h, php_imagick_defs.h, php_imagick_file.h, php_imagick_helpers.h, php_imagick_macros.h, php_imagick_shared.h
This pull request changes various incorrect representations of the name "ImageMagick" to the correct one.
=> Call it "ImageMagick" everywhere

config.m4
First *stable* version available in Ubuntu Lucid
In Debian Squeezy was 5.3.3
For issue #192
=> Raise required php version to 5.3.2

ChangeLog
Wrong class is used in the Changelog. ImagickDraw only has setOpacity, there is no setOpacity in Imagick class.
=> Wrong class mentioned in the Changelog

imagick.c
All sorts of funny things happen when both gmagick and imagick
are loaded, crashes, assertions etc..
Also the standard module must be required.
=> Extension should conflict with gmagick

imagick.c, tests/047_Imagick_convolveImage_6.phpt, tests/098_Imagick_orderedPosterizeImage_basic.phpt, tests/102_Imagick_radialBlurImage_basic.phpt, tests/112_Imagick_roundCorners_basic.phpt, tests/121_Imagick_setImageBias_basic.phpt, tests/123_Imagick_setImageClipMask_basic.phpt, tests/159_Imagick_transformImage_basic.phpt, tests/180_ImagickDraw_matte_basic.phpt, tests/bug20636.phpt
Is it the expected part for #162 ?
If ok, I can probably add some "deprecation" information in PHP manual, such as:
> This method is only available with ImageMagick library version 6.
> Since 3.4.3 this method is deprecated.
>
=> deprecate methods not available in IM 7, see #162

imagick.c, imagick_helpers.c, imagickkernel_class.c, php_imagick_defs.h
This PR is another proposed implementation of #334. Compared to that PR, I have chosen a slightly different approach:
* instead of removing the usages of the TSRM defines, I re-added the empty definitions in order for the code to (potentially) remain compatible with PHP 5. Other checks in the code also provide PHP 5 compatibility so I felt breaking that as part of adding PHP 8 support was not warranted.
* In the same vein, the usage of the `no_separation` field in `zend_fcall_info` is now also checked  based on PHP version.
* this PR also fixes usages of `instanceof_function_ex` which was removed in PHP-8 (by just using `instanceof_function` - in the case of imagick, the two were identical)
* adapt the zend class handlers which are now being called with a `zend_object*` instead of a …
=> PHP-8 compatibility (more extensive)

imagemagick.m4
This PR adds `/opt/homebrew` search prefix in `imagemagick.m4`
Homebrew on new arm machines uses /opt/homebrew as prefix.
So ImageMagick binaries are installed in /opt/homebrew/bin
Ref: https://docs.brew.sh/Installation
=> Add search prefix for homebrew on arm in imagemagick.m4

docker/nixos/shell.nix
Fixes #398. Fixes #399.
I tested this with the NixOS container:
```sh
docker compose up nixos
docker compose exec nixos nix-shell /opt/shell.nix
phpize
./configure --with-imagick=...
make
php -d extension=imagick.so util/check_fonts.php
```
The last command would before output:
```
Fontconfig error: Cannot load default config file
There are 1 fonts:
DejaVu-Sans
```
Now it just says:
```
There are 1 fonts:
DejaVu-Sans
```
This only affects the test setup. The fontconfig stuff is normally prepared by NixOS, but here we are installing standalone Nix packages in Docker, so that's where the difference is coming from.
=> Fix fontconfig error in NixOS container

imagick_class.c, tests/172_ImagickPixel_setColorValueQuantum_basic.phpt
From UPGRADING.INTERNALS
```
- The ZVAL_NEW_ARR() macro has been removed. Use array_init() or ZVAL_ARR
with zend_new_array() instead.
```
=> Issue php81

package.xml
Notice, the "utils" part is also broken
```
Error: File "./utils/functions.php" in package.xml does not exist
Error: File "./utils/FloatInfo.php" in package.xml does not exist
Error: File "./utils/Float32Info.php" in package.xml does not exist
```
Probably worth to add stuff needed to regenerate the arginfo
=> drop duplicates and add stubs in package

ImagickPixel.stub.php, ImagickPixel_arginfo.h, imagickpixel_class.c
In pixel-wand.h, bot IM 6 and 7
```
extern WandExport double
PixelGetAlpha(const PixelWand *) magick_attribute((__pure__)),
PixelGetBlack(const PixelWand *) magick_attribute((__pure__)),
PixelGetBlue(const PixelWand *) magick_attribute((__pure__)),
PixelGetCyan(const PixelWand *) magick_attribute((__pure__)),
PixelGetFuzz(const PixelWand *) magick_attribute((__pure__)),
PixelGetGreen(const PixelWand *) magick_attribute((__pure__)),
PixelGetMagenta(const PixelWand *) magick_attribute((__pure__)),
PixelGetOpacity(const PixelWand *) magick_attribute((__pure__)),
PixelGetRed(const PixelWand *) magick_attribute((__pure__)),
PixelGetYellow(const PixelWand *) magick_attribute((__pure__));
```
Code is OK, arginfo fixed by this PR in 1st commit
Checked in IM 6 and 7  (IndexPacket in 6 is also a …
=> Type issue related to HDRI

package.xml, regen_arginfo.sh
Current script rely on some /usr/local/bin installation of PHP 8
This one should be usable by everyone, and thus can be distributed with the sources
Notice: this PR also make it executable.
=> Improve regen_arginfo.sh to build usable by everyone

.gitignore, tests/031_Imagick_affineTransformImage_basic.phpt, tests/257_Imagick_setImageChannelMask_basic.phpt, tests/264_ImagickDraw_getTextDirection_basic.phpt, tests/274_imagick_setImageAlpha.phpt, tests/281_imagick_houghLineImage_basic.phpt
ignore some files generated during the build and not tracked
ensure all tests create their images in tests directory and properly clean it after the run (--no-clean option exists if image needed for manual check)
=> cleanup git directory

docker/testing8_0/Dockerfile
Just a small fix for the PHP 8 test Dockerfile
=> testing8_0 should install php8.0-common

imagick_file.c, tests/bug81235.phpt
Since `canvas` is a valid pseudo image format, we need to cater to
that.
PS: http://www.imagemagick.org/script/formats.php#pseudo
=> Fix #81235: Imagick::newPseudoImage => open_basedir restriction

tests/bug59378.phpt
Dying in the `SKIPIF` section is insufficient; we need to tell the
runner that we want to skip the test.
=> Add missing skip tag

imagick.c
fixes https://github.com/Imagick/imagick/issues/689
see https://github.com/php/php-src/pull/15391/files
=> Fix removed "php_strtolower" for PHP 8.4

imagick_class.c
This is related to pipeline failure: https://github.com/Imagick/imagick/actions/runs/13470981281/job/37644443027
```
/home/runner/work/imagick/imagick/imagick_class.c: In function 's_add_named_strings':
/home/runner/work/imagick/imagick/imagick_class.c:8601:39: error: the comparison will always evaluate as 'true' for the address of 'val' will never be NULL [-Werror=address]
8601 |                         if (trim->val != NULL) {
|                                       ^~
In file included from /usr/include/php/20230831/Zend/zend.h:27,
from /usr/include/php/20230831/main/php.h:32,
from /home/runner/work/imagick/imagick/php_imagick.h:42,
from /home/runner/work/imagick/imagick/imagick_class.c:21:
/usr/include/php/20230831/Zend/zend_types.h:377:27: note: 'val' declared here
377 |         char …
```
=> Fix invalid val array check in trim

.github/workflows/windows.yml
This PR updates the windows workflow to use php-windows-builder.
Also, adds support to run on a new releases and add builds as release artifacts.
Example release: https://github.com/shivammathur/imagick/releases/tag/3.7.1
=> Switch windows workflow to php-windows-builder

imagickdraw_class.c
Partially, the issue was in the ImageMagick itself and fixed in [6544](https://github.com/ImageMagick/ImageMagick/issues/6544), but still we seem to need release resources here
=> Release memory when replacing drawing wand

Imagick.stub.php, Imagick_arginfo.h, imagick_class.c, package.xml, tests/331_Imagick_getImagesBlob_empty.phpt
PR #616 defined the return type of `getImageBlob()` as nullable, but that is no longer correct because PR #606 changed it to throw an exception instead of returning null.
This PR sets the return type of `getImageBlob()` back to non-nullable and updates `getImagesBlob()` to throw an exception when it fails to get the image contents. This makes both methods behave consistently.
=> Fix `getImage(s)Blob()` return type

imagick.c
* `Zend/zend_smart_string.h` exists since 7.2
* `ext/standard/php_smart_string.h` removed in 8.5.0alpha3
=> use Zend/zend_smart_string.h
